#define PIN_ENA_PUNTE_FATA 6
#define PIN_INPUT_3_PUNTE_FATA 7
#define PIN_INPUT_4_PUNTE_FATA 8

#define PIN_ENB_PUNTE_SPATE 9
#define PIN_INPUT_1_PUNTE_SPATE 12
#define PIN_INPUT_2_PUNTE_SPATE 13

#define PIN_INPUT_IR_STANGA 1  // A1 
#define PIN_INPUT_IR_DREAPTA 3  // A3
